# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
fail_fast: true
exclude: |
    (?x)^(
        README.md|
        gitops.sh|
        lib/macos/enrollment-profiles/automatic-enrollment.dep.json|
        lib/macos/policies/macos-device-health.policies.yml|
        lib/macos/scripts/collect-fleetd-logs.sh|
        lib/macos/scripts/install-santa.sh|
        lib/macos/scripts/macos-password.mobileconfig|
        lib/macos/scripts/uninstall-santa.sh|
        teams/workstations-canary.yml
    )$
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: check-merge-conflict
    -   id: no-commit-to-branch
    -   id: detect-private-key
    -   id: trailing-whitespace
    -   id: check-executables-have-shebangs
    -   id: mixed-line-ending
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-json
    -   id: check-xml
    -   id: check-toml
    -   id: check-added-large-files
-   repo: https://github.com/homebysix/pre-commit-macadmin
    rev: v1.21.0
    hooks:
    -   id: check-plists
    -   id: format-xml-plist
    -   id: check-autopkg-recipe-list
    -   id: check-autopkg-recipes
