# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: check-merge-conflic
    -   id: no-commit-to-branch
    -   id: detect-private-key
    -   id: trailing-whitespace
    -   id: check-executables-have-shebangs
    -   id: mixed-line-ending
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-json
    -   id: check-xml
    -   id: check-toml
    -   id: check-added-large-files
